# Generated by Django 5.1.2 on 2024-10-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NameEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("link", models.URLField(unique=True)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField(default="")),
                ("short_meaning", models.CharField(default="", max_length=255)),
                ("arabic_name", models.CharField(default="", max_length=255)),
                (
                    "quranic_nature",
                    models.CharField(
                        choices=[
                            ("Directly Mentioned", "direct"),
                            ("Indirectly Mentioned", "indirect"),
                        ],
                        default="indirect",
                        max_length=255,
                    ),
                ),
                ("details", models.TextField(default="")),
                (
                    "alternative_spellings",
                    models.ManyToManyField(to="crawler.nameentity"),
                ),
                ("similar_root_names", models.ManyToManyField(to="crawler.nameentity")),
            ],
        ),
    ]
