# Generated by Django 5.1.2 on 2024-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nameentity",
            name="link",
            field=models.URLField(),
        ),
    ]
