# Generated by Django 5.1.2 on 2024-10-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nameentity",
            name="details",
            field=models.TextField(default=""),
        ),
    ]
